use crate::graph::types::{Graph, Node};
use std::env;
use std::fs::File;
use std::io::Write;

const NAME: &str = env!("CARGO_PKG_NAME");
const VERSION: &str = env!("CARGO_PKG_VERSION");

fn fmt_graph_to_dot(g: &Graph) {
    let hm = g.hashmap();

    let mut file = File::create("foo.dot").unwrap();

    // Write header
    writeln!(
        &mut file,
        "\
digraph {{
\t// Generated by {} version {}

\trankdir=LR;
\tdpi=300;
\tedge [color=blue, tailport=ne, headport=nw, arrowtail=dot, arrowhead=normal, arrowsize=.5];
\tnode [shape=box];
",
        NAME, VERSION
    )
    .unwrap();

    // Write nodes
    writeln!(&mut file, "\t// nodes").unwrap();

    for (k, v) in hm.iter() {
        writeln!(&mut file, "\t{} [label=\"{}\"]", k, &v.segment[..5]).unwrap();
    }

    // write edges
    writeln!(&mut file, "\n\t// edges").unwrap();

    for (k, Node { nodes_right, .. }) in hm.iter() {
        for n in nodes_right.iter() {
            writeln!(&mut file, "\t{} -> {}", k, n).unwrap();
        }
    }

    writeln!(&mut file, "}}").unwrap();
}

#[cfg(test)]
mod tests {

    use super::*;
    //use crate::graph::macros;

    const RAW_SEQ: &str = "ACTGATGATCTGATCGGATA";
    const RAW_REF: &str = "GHR38";
    const OFFSET: usize = 23;

    #[test]
    #[ignore]
    fn test_digraph_to_dot() {}
}
